# Generated by Django 3.0.2 on 2020-01-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='lang',
        ),
        migrations.AddField(
            model_name='language',
            name='Lang',
            field=models.CharField(default='English', help_text='Enter a book language(e.g. English)', max_length=50),
        ),
    ]
