# Generated by Django 3.0.2 on 2020-01-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200121_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
